name:                launchpad
version:             0.1.0.0
github:              "lgastako/launchpad"
license:             BSD3
author:              "John Evans"
maintainer:          "lgastako@gmail.com"
copyright:           "2018 John Evans"

extra-source-files:
- README.md
- ChangeLog.md

description:         See README at <https://github.com/lgastako/launchpad#readme>

dependencies:
- base >= 4.7 && < 5
- hmidi
- lens
- protolude
- reflex
- sized-vector
- type-natural

library:
  source-dirs: src
  ghc-options:
  - -Wall
  exposed-modules:
  - Launchpad
  - Launchpad.Colors
  - Launchpad.Demos
  - Launchpad.Prelude

tests:
  launchpad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - launchpad
    - tasty
    - tasty-hspec
    - tasty-quickcheck
