resolver: lts-9.14

packages:
- .

extra-deps:
- constraints-0.8
- equational-reasoning-0.4.1.1
- ghc-typelits-natnormalise-0.4.6
- ghc-typelits-presburger-0.1.1.1
- hmidi-0.2.2.1
- monomorphic-0.0.3.3
- presburger-1.3.1
- ref-tf-0.4.0.1
- reflex-0.4.0.1
- sized-vector-1.4.3.1
- type-natural-0.4.2.0
